kind: pipeline
name: Drone

steps:
 - name: compile
   image: archlinux:base-devel
   environment:
     BOT_TOKEN:
       from_secret: BOT_API_KEY
     GITHUB_TOKEN:
       from_secret: GITHUB_TOKEN
   commands:
      - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
      - pacman -Syu --noconfirm --needed git bc inetutils zip libxml2 python3 jre-openjdk jdk-openjdk flex bison libc++ python-pip
      - cd /drone/src
      - bash kernel.sh